output_dir: wan-lora
logging_dir: logs
seed: 42

report_to:
  wandb: true
  project_name: Spark-Wan-Self-Layer-Distill
  wandb_name: scheduler_step_50_zero_2000
  wandb_notes: ""

parallel_config:
  sp_size: 1

data_config:
  instance_data_root: "scripts/sucai.json"
  height: 480
  width: 832
  fps: 8
  max_num_frames: 81
  dataloader_num_workers: 0

model_config:
  pretrained_lora_path: null
  pretrained_model_name_or_path: "/storage/ysh/Ckpts/Wan2.1-T2V-1.3B-Diffusers/"
  compile_transformer: false
  fsdp_transformer: false
  fsdp_text_encoder: false
  lora_rank: 128
  lora_alpha: 256.0
  lora_dropout: 0.0
  flow_shift: 8.0
  is_train_lora: true
  lora_target_modules: null # set to null but not null inner.

validation_config:
  validation_steps: 100
  validation_prompt: "A stylish woman walks down a Tokyo street filled with warm glowing neon and animated city signage. She wears a black leather jacket, a long red dress, and black boots, and carries a black purse. She wears sunglasses and red lipstick. She walks confidently and casually. The street is damp and reflective, creating a mirror effect of the colorful lights. Many pedestrians walk about."
  validation_prompt_separator: ":::"
  num_validation_videos: 1

training_config:
  resume_from_checkpoint: null
  gradient_accumulation_steps: 1
  max_train_steps: null
  checkpointing_steps: 500
  train_batch_size: 1
  num_train_epochs: 10
  gradient_checkpointing: false
  mixed_precision: fp16
  learning_rate: 0.00001
  lr_scheduler: constant
  optimizer: adamw
  adam_beta1: 0.9
  adam_beta2: 0.99
  adam_weight_decay: 0.0001
  adam_epsilon: 1e-08
  max_grad_norm: 1.0

self_layer_distill_config:
  layers_idx: [4, 8, 12]
  scheduler: step
  zero_step: 2000
  scheduler_config:
    num_steps: 50 # 1000 / 50 = 20
