output_dir: D1_3B_16_2_apt
logging_dir: logs
seed: 42

report_to:
  wandb: true
  project_name: Spark-Wan
  wandb_name: D1_3B_16_2_apt
  wandb_notes: ""
  
parallel_config:
  sp_size: 1

data_config:
  instance_data_root: "scripts/sucai.json"
  height: 480
  width: 832
  fps: 16
  max_num_frames: 81
  dataloader_num_workers: 0

model_config:
  pretrained_lora_path: null
  pretrained_model_name_or_path: "/mnt/data/checkpoints/Wan-AI/Wan2.1-T2V-1.3B-Diffusers"
  compile_transformer: false
  fsdp_transformer: false
  fsdp_text_encoder: false
  fsdp_discriminator: true
  cpu_offload: []
  reshard_after_forward: []
  lora_rank: 256
  lora_alpha: 512.0
  lora_dropout: 0.0
  flow_shift: 7.0
  is_train_lora: false
  is_train_disc_lora: false
  lora_target_modules: null # set to null but not null inner.
  disc_lora_rank: 128
  disc_lora_alpha: 256.0
  disc_lora_dropout: 0.0
  transformer_subfolder: "distill_16"
  disc_target_modules: null # set to null but not null inner.

validation_config:
  validation_steps: 50
  validation_prompt: "A stylish woman walks down a Tokyo street filled with warm glowing neon and animated city signage. She wears a black leather jacket, a long red dress, and black boots, and carries a black purse. She wears sunglasses and red lipstick. She walks confidently and casually. The street is damp and reflective, creating a mirror effect of the colorful lights. Many pedestrians walk about."
  validation_prompt_separator: ":::"
  num_validation_videos: 1
  log_teacher_sample: false

training_config:
  resume_from_checkpoint: null
  gradient_accumulation_steps: 1
  max_train_steps: null
  checkpointing_steps: 200
  train_batch_size: 1
  num_train_epochs: 10
  gradient_checkpointing: true
  disc_gradient_checkpointing: true
  mixed_precision: bf16
  learning_rate: 0.000001
  lr_scheduler: constant
  optimizer: adamw
  adam_beta1: 0.0
  adam_beta2: 0.99
  adam_weight_decay: 0.0001
  adam_epsilon: 1e-08
  max_grad_norm: 1.0

apt_distill_config:
  student_step: 2
  disc_interval: 2
  disc_weight: 1.0
  scheduler_type: UniPC
  discriminator_dropout: 0.0
  discriminator_copy_num_layers: 30
  discriminator_head_type: seaweed
  discriminator_seaweed_output_layer: [-1, -9, -17]
  disc_loss_type: d_loss